# Verification Statuses
VERIFICATION_STATUS_PENDING = "pending"
VERIFICATION_STATUS_ID_UPLOADED = "id_uploaded"
VERIFICATION_STATUS_SELFIE_UPLOADED = "selfie_uploaded"
VERIFICATION_STATUS_UNDER_REVIEW = "under_review"
VERIFICATION_STATUS_VERIFIED = "verified"
VERIFICATION_STATUS_FAILED = "failed"

VERIFICATION_STATUS_CHOICES = [
    (VERIFICATION_STATUS_PENDING, "Pending"),
    (VERIFICATION_STATUS_ID_UPLOADED, "ID Uploaded"),
    (VERIFICATION_STATUS_SELFIE_UPLOADED, "Selfie Uploaded"),
    (VERIFICATION_STATUS_UNDER_REVIEW, "Under Review"),
    (VERIFICATION_STATUS_VERIFIED, "Verified"),
    (VERIFICATION_STATUS_FAILED, "Failed"),
]

# Verification Methods
VERIFICATION_METHOD_INTERNAL = "internal"
VERIFICATION_METHOD_NAFATH = "nafath"
VERIFICATION_METHOD_ABSHER = "absher"

VERIFICATION_METHOD_CHOICES = [
    (VERIFICATION_METHOD_INTERNAL, "Internal"),
    (VERIFICATION_METHOD_NAFATH, "Nafath"),
    (VERIFICATION_METHOD_ABSHER, "Absher"),
]

# Verification Event Types
EVENT_ID_FRONT_UPLOADED = "ID_FRONT_UPLOADED"
EVENT_ID_BACK_UPLOADED = "ID_BACK_UPLOADED"
EVENT_SELFIE_UPLOADED = "SELFIE_UPLOADED"
EVENT_VERIFICATION_STARTED = "VERIFICATION_STARTED"
EVENT_VERIFICATION_COMPLETED = "VERIFICATION_COMPLETED"
EVENT_VERIFICATION_FAILED = "VERIFICATION_FAILED"
EVENT_ID_OCR_STARTED = "ID_OCR_STARTED"
EVENT_ID_OCR_COMPLETED = "ID_OCR_COMPLETED"
EVENT_ID_OCR_FAILED = "ID_OCR_FAILED"

VERIFICATION_EVENT_CHOICES = [
    (EVENT_ID_FRONT_UPLOADED, "ID Front Uploaded"),
    (EVENT_ID_BACK_UPLOADED, "ID Back Uploaded"),
    (EVENT_SELFIE_UPLOADED, "Selfie Uploaded"),
    (EVENT_VERIFICATION_STARTED, "Verification Started"),
    (EVENT_VERIFICATION_COMPLETED, "Verification Completed"),
    (EVENT_VERIFICATION_FAILED, "Verification Failed"),
    (EVENT_ID_OCR_STARTED, "ID OCR Started"),
    (EVENT_ID_OCR_COMPLETED, "ID OCR Completed"),
    (EVENT_ID_OCR_FAILED, "ID OCR Failed"),
]

