from django.urls import path
from .views import (
    DocumentUploadView,
    EnvelopeCreateView,
    EnvelopePatchView,
    SendEnvelopeView,
    SigningView,
    SigningDocumentView,
    SigningSignedDocumentView,
    SigningDownloadView,
    DashboardView,
    PackageDetailView,
    PackageListView,
    TemplateListCreateView,
    TemplateDetailView,
    PackageSignedPreviewView,
    PackageSignedDownloadView,
    RegisterView,
    LoginView,
    LogoutView,
    UserMeView,
    PackageCertificateDownloadView,
    SigningCertificateDownloadView,
    ContractAnalyzeView,
    ConfirmCandidatesView,
    IgnoreCandidatesView,
    SignerVerificationIDView,
    SignerVerificationSelfieView,
    SignerVerificationDetailView,
    SignerVerificationIDExtractView,
    SignerAuthorizationStatusView,
    TermsAcceptanceView,
    SendEmailOTPView,
    VerifyEmailOTPView,
)

urlpatterns = [
    path('documents/upload/', DocumentUploadView.as_view()),
    path('envelopes/', EnvelopeCreateView.as_view()),
    path('envelopes/<int:pk>/', EnvelopePatchView.as_view()),
    path('envelopes/<int:envelope_id>/send/', SendEnvelopeView.as_view()),
    path('sign/<uuid:token>/', SigningView.as_view()),
    path('sign/<uuid:token>/document/', SigningDocumentView.as_view(), name='signing-document'),
    path('sign/<uuid:token>/signed/', SigningSignedDocumentView.as_view(), name='signing-signed'),
    path('sign/<uuid:token>/download/', SigningDownloadView.as_view(), name='signing-download'),
    path('sign/<uuid:token>/certificate/download/', SigningCertificateDownloadView.as_view(), name='signing-certificate-download'),
    path('dashboard/', DashboardView.as_view()),
    path('packages/', PackageListView.as_view()),
    path('packages/<int:pk>/', PackageDetailView.as_view()),
    path('packages/<int:pk>/preview/', PackageSignedPreviewView.as_view(), name='package-signed-preview'),
    path('packages/<int:pk>/download/', PackageSignedDownloadView.as_view(), name='package-signed-download'),
    path('packages/<int:pk>/certificate/download/', PackageCertificateDownloadView.as_view(), name='package-certificate-download'),
    path('templates/', TemplateListCreateView.as_view(), name='template-list-create'),
    path('templates/<int:pk>/', TemplateDetailView.as_view(), name='template-detail'),
    path('auth/register/', RegisterView.as_view(), name='register'),
    path('auth/login/', LoginView.as_view(), name='login'),
    path('auth/logout/', LogoutView.as_view(), name='logout'),
    path('auth/me/', UserMeView.as_view(), name='user-me'),
    path('contracts/analyze/', ContractAnalyzeView.as_view(), name='contract-analyze'),
    path('envelopes/<int:envelope_id>/confirm-candidates/', ConfirmCandidatesView.as_view(), name='confirm-candidates'),
    path('envelopes/<int:envelope_id>/ignore-candidates/', IgnoreCandidatesView.as_view(), name='ignore-candidates'),
    path('participants/<int:participant_id>/verification/id/', SignerVerificationIDView.as_view(), name='signer-verification-id'),
    path('participants/<int:participant_id>/verification/selfie/', SignerVerificationSelfieView.as_view(), name='signer-verification-selfie'),
    path('participants/<int:participant_id>/verification/extract-id/', SignerVerificationIDExtractView.as_view(), name='signer-verification-extract-id'),
    path('participants/<int:participant_id>/verification/', SignerVerificationDetailView.as_view(), name='signer-verification-detail'),
    path('participants/<int:participant_id>/authorization-status/', SignerAuthorizationStatusView.as_view(), name='authorization-status'),
    path('participants/<int:participant_id>/accept-terms/', TermsAcceptanceView.as_view(), name='accept-terms'),
    path('participants/<int:participant_id>/send-email-otp/', SendEmailOTPView.as_view(), name='send-email-otp'),
    path('participants/<int:participant_id>/verify-email-otp/', VerifyEmailOTPView.as_view(), name='verify-email-otp'),
]