from django.urls import path
from .views import (
    DocumentUploadView,
    EnvelopeCreateView,
    SendEnvelopeView,
    SigningView,
    SigningDocumentView,
    SigningSignedDocumentView,
    SigningDownloadView,
    DashboardView,
    PackageDetailView,
    PackageListView,
    TemplateListCreateView,
    TemplateDetailView,
    PackageSignedPreviewView,
    PackageSignedDownloadView,
    RegisterView,
    LoginView,
    LogoutView,
    UserMeView,
    PackageCertificateDownloadView,
    SigningCertificateDownloadView,
)

urlpatterns = [
    path('documents/upload/', DocumentUploadView.as_view()),
    path('envelopes/', EnvelopeCreateView.as_view()),
    path('envelopes/<int:envelope_id>/send/', SendEnvelopeView.as_view()),
    path('sign/<uuid:token>/', SigningView.as_view()),
    path('sign/<uuid:token>/document/', SigningDocumentView.as_view(), name='signing-document'),
    path('sign/<uuid:token>/signed/', SigningSignedDocumentView.as_view(), name='signing-signed'),
    path('sign/<uuid:token>/download/', SigningDownloadView.as_view(), name='signing-download'),
    path('sign/<uuid:token>/certificate/download/', SigningCertificateDownloadView.as_view(), name='signing-certificate-download'),
    path('dashboard/', DashboardView.as_view()),
    path('packages/', PackageListView.as_view()),
    path('packages/<int:pk>/', PackageDetailView.as_view()),
    path('packages/<int:pk>/preview/', PackageSignedPreviewView.as_view(), name='package-signed-preview'),
    path('packages/<int:pk>/download/', PackageSignedDownloadView.as_view(), name='package-signed-download'),
    path('packages/<int:pk>/certificate/download/', PackageCertificateDownloadView.as_view(), name='package-certificate-download'),
    path('templates/', TemplateListCreateView.as_view(), name='template-list-create'),
    path('templates/<int:pk>/', TemplateDetailView.as_view(), name='template-detail'),
    path('auth/register/', RegisterView.as_view(), name='register'),
    path('auth/login/', LoginView.as_view(), name='login'),
    path('auth/logout/', LogoutView.as_view(), name='logout'),
    path('auth/me/', UserMeView.as_view(), name='user-me'),
]