# Generated by Django 5.2.14 on 2026-05-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='envelope',
            name='signature_page',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='envelope',
            name='signature_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='envelope',
            name='signature_y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
