# Generated by Django 5.2.14 on 2026-05-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0002_envelope_signature_page_envelope_signature_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='envelope',
            name='render_height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='envelope',
            name='render_width',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
