# Generated by Django 5.2.14 on 2026-05-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0003_add_render_dims_to_envelope'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envelope',
            name='render_height',
        ),
        migrations.RemoveField(
            model_name='envelope',
            name='render_width',
        ),
        migrations.RemoveField(
            model_name='envelope',
            name='signature_x',
        ),
        migrations.RemoveField(
            model_name='envelope',
            name='signature_y',
        ),
        migrations.AddField(
            model_name='envelope',
            name='signature_x_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='envelope',
            name='signature_y_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
