# Generated by Django 5.2.14 on 2026-05-31 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0004_remove_envelope_render_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='envelope',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='envelope',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='envelope',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('signed', 'Signed'), ('completed', 'Completed'), ('expired', 'Expired'), ('declined', 'Declined')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('signer', 'Signer'), ('approver', 'Approver'), ('reviewer', 'Reviewer'), ('cc', 'CC')], max_length=20)),
                ('order', models.PositiveIntegerField(default=1)),
                ('has_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('envelope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='esign.envelope')),
            ],
        ),
    ]
