# Generated by Django 5.2.14 on 2026-05-31 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0005_envelope_description_envelope_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='role',
            field=models.CharField(choices=[('signer', 'Signer'), ('approver', 'Approver'), ('reviewer', 'Reviewer'), ('cc', 'CC')], default='signer', max_length=20),
        ),
    ]
