# Generated by Django 5.2.14 on 2026-06-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0006_alter_participant_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='step_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
