# Generated by Django 5.2.14 on 2026-06-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0007_participant_step_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('viewed', 'Viewed'), ('completed', 'Completed'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
    ]
