# Generated by Django 5.2.14 on 2026-06-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0008_participant_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('viewed', 'Viewed'), ('completed', 'Completed'), ('declined', 'Declined'), ('returned', 'Returned')], default='pending', max_length=20),
        ),
    ]
