# Generated by Django 5.2.14 on 2026-06-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0010_participanttoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='envelope',
            name='additional_recipients',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='envelope',
            name='allow_printing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='envelope',
            name='send_final_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='envelope',
            name='send_reminders',
            field=models.BooleanField(default=False),
        ),
    ]
