# Generated by Django 5.2.14 on 2026-06-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0011_envelope_additional_recipients_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(default='General', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=20)),
                ('workflow_definition', models.JSONField(blank=True, default=list)),
                ('request_settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
