# Generated by Django 5.2.14 on 2026-06-04 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0012_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(choices=[('signature', 'Signature'), ('date', 'Date'), ('text', 'Text'), ('checkbox', 'Checkbox')], max_length=20)),
                ('page', models.IntegerField()),
                ('x_ratio', models.FloatField()),
                ('y_ratio', models.FloatField()),
                ('required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('envelope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='esign.envelope')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='esign.participant')),
            ],
        ),
    ]
