# Generated by Django 5.2.14 on 2026-06-08 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0015_backfill_owners'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletionCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='certificates/')),
                ('final_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('envelope', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completion_certificate', to='esign.envelope')),
            ],
        ),
    ]
