# Generated by Django 5.2.14 on 2026-06-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0016_completioncertificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='completioncertificate',
            name='certificate_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
    ]
