# Generated by Django 5.2.14 on 2026-06-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0017_completioncertificate_certificate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='event',
            field=models.CharField(max_length=255),
        ),
    ]
