# Generated by Django 5.2.14 on 2026-06-18 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0019_backfill_participants'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractAnalysisAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representative_name', models.CharField(blank=True, max_length=512)),
                ('representative_title', models.CharField(blank=True, max_length=512)),
                ('authority_clause', models.TextField(blank=True)),
                ('authority_detected', models.BooleanField(default=False)),
                ('ocr_provider', models.CharField(blank=True, max_length=50)),
                ('ocr_confidence', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('envelope', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_audit', to='esign.envelope')),
            ],
        ),
        migrations.CreateModel(
            name='RepresentativeCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(blank=True, max_length=255)),
                ('name_ar', models.CharField(blank=True, max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255)),
                ('title_ar', models.CharField(blank=True, max_length=255)),
                ('authority_clause', models.TextField(blank=True)),
                ('selected', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('envelope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representative_candidates', to='esign.envelope')),
            ],
        ),
    ]
