# Generated by Django 5.2.14 on 2026-06-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0020_contractanalysisaudit_representativecandidate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='representativecandidate',
            name='selected',
        ),
        migrations.AddField(
            model_name='representativecandidate',
            name='converted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='representativecandidate',
            name='ignored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='representativecandidate',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('converted', 'Converted'), ('ignored', 'Ignored')], default='pending', max_length=20),
        ),
    ]
