# Generated by Django 5.2.14 on 2026-06-23 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0021_remove_representativecandidate_selected_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignerVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('id_uploaded', 'ID Uploaded'), ('selfie_uploaded', 'Selfie Uploaded'), ('under_review', 'Under Review'), ('verified', 'Verified'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('verification_method', models.CharField(choices=[('internal', 'Internal'), ('nafath', 'Nafath'), ('absher', 'Absher')], default='internal', max_length=50)),
                ('national_id_number', models.CharField(blank=True, max_length=50)),
                ('national_id_front', models.FileField(blank=True, null=True, upload_to='verification/id_front/')),
                ('national_id_back', models.FileField(blank=True, null=True, upload_to='verification/id_back/')),
                ('selfie_image', models.FileField(blank=True, null=True, upload_to='verification/selfie/')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='esign.participant')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ID_FRONT_UPLOADED', 'ID Front Uploaded'), ('ID_BACK_UPLOADED', 'ID Back Uploaded'), ('SELFIE_UPLOADED', 'Selfie Uploaded'), ('VERIFICATION_STARTED', 'Verification Started'), ('VERIFICATION_COMPLETED', 'Verification Completed'), ('VERIFICATION_FAILED', 'Verification Failed')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('signer_verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='esign.signerverification')),
            ],
        ),
    ]
