# Generated by Django 5.2.14 on 2026-06-23 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0022_signerverification_verificationevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationevent',
            name='event_type',
            field=models.CharField(choices=[('ID_FRONT_UPLOADED', 'ID Front Uploaded'), ('ID_BACK_UPLOADED', 'ID Back Uploaded'), ('SELFIE_UPLOADED', 'Selfie Uploaded'), ('VERIFICATION_STARTED', 'Verification Started'), ('VERIFICATION_COMPLETED', 'Verification Completed'), ('VERIFICATION_FAILED', 'Verification Failed'), ('ID_OCR_STARTED', 'ID OCR Started'), ('ID_OCR_COMPLETED', 'ID OCR Completed'), ('ID_OCR_FAILED', 'ID OCR Failed')], max_length=50),
        ),
        migrations.CreateModel(
            name='NationalIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('saudi_id', 'Saudi National ID'), ('iqama', 'Iqama'), ('passport', 'Passport')], default='saudi_id', max_length=30)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('national_id_number', models.CharField(blank=True, max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('id_photo', models.ImageField(blank=True, null=True, upload_to='verification/id_photo/')),
                ('ocr_provider', models.CharField(default='azure', max_length=50)),
                ('ocr_confidence', models.FloatField(blank=True, null=True)),
                ('raw_text', models.TextField(blank=True)),
                ('extraction_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('failure_reason', models.CharField(blank=True, choices=[('no_text_detected', 'No text detected'), ('parsing_failed', 'Parsing failed'), ('azure_error', 'Azure OCR service error')], max_length=50, null=True)),
                ('extracted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='national_identity', to='esign.signerverification')),
            ],
        ),
    ]
