# Generated by Django 5.2.14 on 2026-06-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0023_alter_verificationevent_event_type_nationalidentity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nationalidentity',
            name='document_type',
            field=models.CharField(choices=[('saudi_id', 'Saudi National ID'), ('iqama', 'Iqama'), ('passport', 'Passport'), ('aadhaar', 'Aadhaar'), ('unknown', 'Unknown')], default='unknown', max_length=30),
        ),
    ]
