# Generated by Django 5.2.14 on 2026-06-24 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0024_alter_nationalidentity_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='envelope',
            name='email_otp_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='envelope',
            name='face_biometric_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='envelope',
            name='national_id_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='envelope',
            name='representative_match_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='envelope',
            name='sms_otp_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='envelope',
            name='terms_acceptance_required',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ParticipantAuthorizationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_verified', models.BooleanField(default=False)),
                ('sms_verified', models.BooleanField(default=False)),
                ('accepted_terms', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='authorization_state', to='esign.participant')),
            ],
        ),
    ]
