# Generated by Django 5.2.14 on 2026-06-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0025_envelope_email_otp_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantauthorizationstate',
            name='accepted_terms_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participantauthorizationstate',
            name='terms_version',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
