# Generated by Django 5.2.14 on 2026-06-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0026_participantauthorizationstate_accepted_terms_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantauthorizationstate',
            name='email_otp_code',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
        migrations.AddField(
            model_name='participantauthorizationstate',
            name='email_otp_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participantauthorizationstate',
            name='email_otp_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participantauthorizationstate',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
