# Generated by Django 5.2.14 on 2026-06-24 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0027_participantauthorizationstate_email_otp_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=30)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_session', to='esign.participant')),
            ],
        ),
        migrations.CreateModel(
            name='BiometricVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=30)),
                ('similarity_score', models.FloatField(blank=True, null=True)),
                ('liveness_score', models.FloatField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, max_length=255)),
                ('failure_reason', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_verification', to='esign.participant')),
                ('verification_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_verification', to='esign.verificationsession')),
            ],
        ),
    ]
