# Generated by Django 5.2.14 on 2026-06-24 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0028_verificationsession_biometricverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignerIdentityVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('verified', 'Verified'), ('failed', 'Failed'), ('requires_manual_review', 'Requires Manual Review')], default='pending', max_length=50)),
                ('document_image', models.FileField(blank=True, null=True, upload_to='identity/documents/')),
                ('reference_face_image', models.FileField(blank=True, null=True, upload_to='identity/faces/')),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('national_id_number', models.CharField(blank=True, max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('document_type', models.CharField(blank=True, max_length=50)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signer_identity_verification', to='esign.participant')),
            ],
        ),
    ]
