# Generated by Django 5.2.14 on 2026-06-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0029_signeridentityverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='signeridentityverification',
            name='identity_match_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signeridentityverification',
            name='identity_matched',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
