# Generated by Django 5.2.14 on 2026-06-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0031_webhooksubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantauthorizationstate',
            name='email_otp_code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
