# Generated by Django 5.2.14 on 2026-06-30 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0032_alter_participantauthorizationstate_email_otp_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signerverification',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='verificationevent',
            name='signer_verification',
        ),
        migrations.DeleteModel(
            name='NationalIdentity',
        ),
        migrations.DeleteModel(
            name='SignerVerification',
        ),
        migrations.DeleteModel(
            name='VerificationEvent',
        ),
    ]
