# Generated by Django 5.2.14 on 2026-07-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0034_document_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='signeridentityverification',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='signeridentityverification',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signeridentityverification',
            name='ocr_provider',
            field=models.CharField(blank=True, default='gemini', max_length=50),
        ),
        migrations.AddField(
            model_name='signeridentityverification',
            name='raw_ocr_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
