# Generated by Django 5.2.14 on 2026-07-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0035_signeridentityverification_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signeridentityverification',
            name='full_name_ar',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='signeridentityverification',
            name='full_name_en',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
