# Generated by Django 5.2.14 on 2026-07-05 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0036_signeridentityverification_full_name_ar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OcrCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('raw_ocr_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContractAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_hash', models.CharField(db_index=True, max_length=64)),
                ('provider', models.CharField(default='gemini', max_length=50)),
                ('representatives', models.JSONField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='esign.document')),
            ],
        ),
    ]
