# Generated by Django 5.2.14 on 2026-10-06 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0037_ocrcache_contractanalysis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='participantauthorizationstate',
            name='manual_review_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participantauthorizationstate',
            name='manual_review_decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participantauthorizationstate',
            name='manual_review_decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_review_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='participantauthorizationstate',
            name='manual_review_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='participantauthorizationstate',
            name='manual_review_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participantauthorizationstate',
            name='manual_review_resubmit_step',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
