# Generated by Django 5.2.18 on 2026-10-07 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0038_participantauthorizationstate_manual_review_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='entry_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='prev_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='signeddocument',
            name='completion_seal',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='signeddocument',
            name='visual_document_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
